kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-inventory
      version: v01
  template:
    metadata:
      labels:
        app: store-inventory
        version: v01
    spec:
      containers:
        - name: store-inventory
          image: cembo/store_inventory:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: store-inventory
  ports:
    - name: store-inventory
      protocol: TCP
      port: 80
      targetPort: 80