kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
      version: v01
  template:
    metadata:
      labels:
        app: inventory
        version: v01
    spec:
      containers:
        - name: inventory
          image: cembo/store_inventory:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "inventory-mssql-clusterip-srv"
            - name: DB_NAME
              value: "Store_Inventory"
            - name: DB_USER
              value: "StoreUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access
apiVersion: v1
kind: Service
metadata:
  name: inventory-nodeport-srv
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
