kind: Deployment
apiVersion: apps/v1
metadata:
  name: scheduler-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
      version: v01
  template:
    metadata:
      labels:
        app: scheduler
        version: v01
    spec:
      containers:
        - name: scheduler
          image: cembo/store_scheduler:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "scheduler-mssql-clusterip-srv"
            - name: DB_NAME
              value: "Store_Scheduler"
            - name: DB_USER
              value: "StoreUser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: scheduler
  ports:
    - name: scheduler
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: scheduler-nodeport-srv
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005