kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
      version: v01
  template:
    metadata:
      labels:
        app: identity
        version: v01
    spec:
      containers:
        - name: identity
          image: cembo/store_identity:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - name: identity
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: identity-nodeport-srv
spec:
  type: NodePort
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001