kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-amqp-publisher-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-amqp-publisher
      version: v01
  template:
    metadata:
      labels:
        app: inventory-amqp-publisher
        version: v01
    spec:
      containers:
        - name: inventory-amqp-publisher
          image: cembo/store_inventory_amqp_publisher:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-publisher-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: inventory-amqp-publisher
  ports:
    - name: inventory-amqp-publisher
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: inventory-amqp-publisher-nodeport-srv
spec:
  type: NodePort
  selector:
    app: inventory-amqp-publisher
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30091