apiVersion: batch/v1
kind: Job
metadata:
  name: inventory-amqp-mssql-init
spec:
  template:
    spec:
      containers:
        - name: mssql-init
          image: mcr.microsoft.com/mssql-tools
          command:
            - /bin/sh
            - -c
            - |
              sleep 40  # wait for SQL Server startup
              /opt/mssql-tools/bin/sqlcmd -S inventory-amqp-mssql-clusterip-srv -U sa -P "$SA_PASSWORD" -Q "
              IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = 'StoreUser')
              BEGIN
                CREATE LOGIN StoreUser WITH PASSWORD='$(DB_PASSWORD)', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
              END;
              IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Store_Inventory_AMQP')
              BEGIN
                CREATE DATABASE Store_Inventory_AMQP;
              END;
              USE Store_Inventory_AMQP;
              IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'StoreUser')
              BEGIN
                CREATE USER StoreUser FOR LOGIN StoreUser;
              END;
              ALTER ROLE db_datareader ADD MEMBER StoreUser;
              ALTER ROLE db_datawriter ADD MEMBER StoreUser;
              GRANT EXECUTE TO StoreUser;"
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SA_PASSWORD
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: STOREUSER_PASSWORD
      restartPolicy: OnFailure
