kind: Deployment
apiVersion: apps/v1
metadata:
  name: static-content-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-static-content
      version: v01
  template:
    metadata:
      labels:
        app: store-static-content
        version: v01
    spec:
      containers:
        - name: store-static-content
          image: cembo/store_static_content:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: static-content-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: store-static-content
  ports:
    - name: store-static-content
      protocol: TCP
      port: 80
      targetPort: 80