kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-gateway-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: v01
  template:
    metadata:
      labels:
        app: api-gateway
        version: v01
    spec:
      containers:
        - name: api-gateway
          image: cembo/store_api_gateway:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 80
      targetPort: 80

---

# development - optional - for direct access

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport-srv
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000